# Quasi-Newton Hessian Update Functions
# ======================================
#
# Implements Algorithm 4a: BFGS, SR1, L-BFGS, and L-SR1 update formulas
# for maintaining Hessian approximations in the QN-ARC optimizer.


#' SR1 (Symmetric Rank-1) Hessian Update
#'
#' Updates the Hessian approximation using the SR1 formula. Unlike BFGS,
#' SR1 can represent indefinite matrices, making it ideal for ARC which
#' naturally handles negative curvature.
#'
#' @param b Current Hessian approximation (n x n symmetric matrix).
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#' @param skip_tol Tolerance for skip test (default: 1e-8). Update is skipped
#'   if |r'*s| < skip_tol * ||r|| * ||s||.
#' @param skip_count Current count of consecutive skipped updates.
#' @param restart_threshold Number of consecutive skips before restart
#'   (default: 5).
#'
#' @return A list with components:
#'   \item{b}{Updated Hessian approximation (n x n matrix).}
#'   \item{skipped}{Logical indicating if update was skipped.}
#'   \item{skip_count}{Updated skip counter (reset to 0 if update applied or
#'     restart triggered).}
#'   \item{restarted}{Logical indicating if b was reset to scaled identity.}
#'
#' @details
#' The SR1 update formula is:
#' \deqn{B_{k+1} = B_k + \frac{r r^T}{r^T s}}
#' where \eqn{r = y - B_k s}.
#'
#' The update is skipped when the denominator is too small relative to the
#' norms of r and s, which prevents numerical instability. After too many
#' consecutive skips, the approximation is reset using Barzilai-Borwein
#' scaling.
#'
#' @references
#' Algorithm 4a in design/pseudocode.qmd
#'
#' Conn, A. R., Gould, N. I., & Toint, P. L. (1991). Convergence of
#' quasi-Newton matrices generated by the symmetric rank one update.
#' Mathematical Programming, 50(1-3), 177-195.
#'
#' @keywords internal
update_sr1 <- function(b, s, y,
                       skip_tol = 1e-8,
                       skip_count = 0L,
                       restart_threshold = 5L) {
  # Compute residual: how far b is from satisfying secant equation
  r <- y - b %*% s
  r <- as.vector(r)

  # Norms for skip test
  r_norm <- sqrt(sum(r^2))
  s_norm <- sqrt(sum(s^2))

  # Skip if s is essentially zero (no step taken)
  if (s_norm < .Machine$double.eps) {
    return(list(b = b, skipped = TRUE, skip_count = skip_count, restarted = FALSE))
  }

  # Skip if r is essentially zero (B already satisfies secant equation)
  if (r_norm < .Machine$double.eps * s_norm) {
    return(list(b = b, skipped = TRUE, skip_count = skip_count, restarted = FALSE))
  }

  # Denominator of SR1 update
  denom <- sum(r * s)

  # Skip test: avoid division by near-zero denominator
  if (abs(denom) >= skip_tol * r_norm * s_norm) {
    # Apply SR1 update: B_{k+1} = B_k + (r r^T) / denom
    b_updated <- b + outer(r, r) / denom

    return(list(
      b = b_updated,
      skipped = FALSE,
      skip_count = 0L,
      restarted = FALSE
    ))
  }

  # Denominator too small - skip update
  skip_count <- skip_count + 1L

  # Check if restart is needed
  if (skip_count > restart_threshold) {
    # Restart with Barzilai-Borwein scaling: gamma = (y'*s) / (s'*s)
    ys <- sum(y * s)
    ss <- sum(s * s)

    if (ss > .Machine$double.eps && abs(ys) > .Machine$double.eps) {
      gamma <- ys / ss
    } else {
      gamma <- 1.0
    }

    # Reset to scaled identity
    n <- length(s)
    b_updated <- gamma * diag(n)

    return(list(
      b = b_updated,
      skipped = TRUE,
      skip_count = 0L,
      restarted = TRUE
    ))
  }

  # Skip without restart
  return(list(
    b = b,
    skipped = TRUE,
    skip_count = skip_count,
    restarted = FALSE
  ))
}


#' BFGS (Broyden-Fletcher-Goldfarb-Shanno) Hessian Update
#'
#' Updates the Hessian approximation using the BFGS formula. BFGS maintains
#' positive definiteness when the curvature condition y'*s > 0 is satisfied.
#'
#' @param b Current Hessian approximation (n x n symmetric positive definite
#'   matrix).
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#'
#' @return A list with components:
#'   \item{b}{Updated Hessian approximation (n x n matrix).}
#'   \item{skipped}{Logical indicating if update was skipped due to curvature
#'     condition violation.}
#'
#' @details
#' The BFGS update formula is:
#' \deqn{B_{k+1} = B_k - \frac{B_k s s^T B_k}{s^T B_k s} + \frac{y y^T}{y^T s}}
#'
#' The update is skipped when the curvature condition \eqn{y^T s > 0} is
#' violated. This can happen on nonconvex problems. When skipped, the previous
#' approximation is retained.
#'
#' Note: BFGS maintains positive definiteness, which wastes ARC's ability to
#' handle indefinite Hessians. Consider using SR1 for nonconvex problems.
#'
#' @references
#' Algorithm 4a in design/pseudocode.qmd
#'
#' Nocedal, J., & Wright, S. J. (2006). Numerical Optimization (2nd ed.).
#' Springer. Section 6.1.
#'
#' @keywords internal
update_bfgs <- function(b, s, y) {
  # Curvature condition: y's > 0 required for positive definiteness
  ys <- sum(y * s)

  if (ys <= .Machine$double.eps) {
    # Curvature condition violated - skip update
    return(list(b = b, skipped = TRUE))
  }

  # Compute B*s for use in update
  bs <- as.vector(b %*% s)
  sbs <- sum(s * bs)

  # BFGS update: B_{k+1} = B_k - (B*s)(B*s)' / (s'*B*s) + y*y' / (y'*s)
  b_updated <- b - outer(bs, bs) / sbs + outer(y, y) / ys

  list(b = b_updated, skipped = FALSE)
}


# =============================================================================
# Limited-Memory Variants
# =============================================================================
# These functions work with history lists instead of explicit matrices.
# The Hessian is represented implicitly via two-loop recursion.


#' L-BFGS History Update
#'
#' Updates the L-BFGS history by adding a new (s, y) pair and dropping the
#' oldest if the memory limit is exceeded.
#'
#' @param history List with components `s` (list of step vectors) and `y`
#'   (list of gradient differences). Can be NULL for first iteration.
#' @param s New step vector: s = x_new - x_old.
#' @param y New gradient difference: y = g_new - g_old.
#' @param m Maximum number of pairs to store (default: 10).
#'
#' @return Updated history list with components:
#'   \item{s}{List of step vectors (most recent last).}
#'   \item{y}{List of gradient differences.}
#'   \item{rho}{Vector of 1/(y'*s) values for each pair.}
#'   \item{gamma}{Scaling factor for initial Hessian: (y'*s)/(y'*y).}
#'
#' @details
#' L-BFGS stores the m most recent (s, y) pairs and represents the Hessian
#' implicitly. The scaling gamma is the Barzilai-Borwein estimate from the
#' most recent pair.
#'
#' @keywords internal
update_lbfgs <- function(history, s, y, m = 10L) {
  # Curvature condition check
  ys <- sum(y * s)

  if (ys <= .Machine$double.eps) {
    # Skip this pair - curvature condition violated
    if (is.null(history)) {
      return(list(s = list(), y = list(), rho = numeric(0), gamma = 1.0))
    }
    return(history)
  }

  # Initialize history if NULL
  if (is.null(history)) {
    history <- list(s = list(), y = list(), rho = numeric(0), gamma = 1.0)
  }

  # Add new pair
  history$s <- c(history$s, list(s))
  history$y <- c(history$y, list(y))
  history$rho <- c(history$rho, 1.0 / ys)

  # Drop oldest if exceeding memory limit
  k <- length(history$s)
  if (k > m) {
    history$s <- history$s[(k - m + 1):k]
    history$y <- history$y[(k - m + 1):k]
    history$rho <- history$rho[(k - m + 1):k]
  }

  # Update scaling: gamma = (y'*s) / (y'*y) from most recent pair
  yy <- sum(y * y)
  if (yy > .Machine$double.eps) {
    history$gamma <- ys / yy
  }

  history
}


#' L-BFGS Two-Loop Recursion
#'
#' Computes the product B*g using the two-loop recursion algorithm, where B
#' is the L-BFGS approximation represented by the history.
#'
#' @param history L-BFGS history list from `update_lbfgs`.
#' @param g Vector to multiply by B (typically the gradient).
#'
#' @return The product B*g as a numeric vector.
#'
#' @details
#' The two-loop recursion computes B*g in O(mn) operations where m is the
#' history length and n is the dimension, avoiding explicit formation of the
#' n x n matrix B.
#'
#' The algorithm:
#' 1. Backward loop: compute alpha_i and update q
#' 2. Initial scaling: r = gamma * q
#' 3. Forward loop: update r using beta_i
#'
#' @references
#' Nocedal, J., & Wright, S. J. (2006). Numerical Optimization (2nd ed.).
#' Springer. Algorithm 7.4.
#'
#' @keywords internal
lbfgs_multiply <- function(history, g) {
  k <- length(history$s)

  # Handle empty history - return gamma * g
  if (k == 0) {
    return(history$gamma * g)
  }

  # Allocate storage for alpha values
  alpha <- numeric(k)

  # First loop: go backwards through history
  q <- g
  for (i in k:1) {
    alpha[i] <- history$rho[i] * sum(history$s[[i]] * q)
    q <- q - alpha[i] * history$y[[i]]
  }

  # Initial Hessian: H_0 = gamma * I
  r <- history$gamma * q

  # Second loop: go forwards through history
  for (i in 1:k) {
    beta <- history$rho[i] * sum(history$y[[i]] * r)
    r <- r + (alpha[i] - beta) * history$s[[i]]
  }

  r
}


#' L-SR1 History Update
#'
#' Updates the L-SR1 history by adding a new (s, y) pair if it passes the
#' skip test.
#'
#' @param history List with components `s`, `y`, and `gamma`. Can be NULL.
#' @param s New step vector: s = x_new - x_old.
#' @param y New gradient difference: y = g_new - g_old.
#' @param m Maximum number of pairs to store (default: 10).
#' @param skip_tol Tolerance for skip test (default: 1e-8).
#' @param b_times_s Product B*s where B is current approximation. If NULL,
#'   uses gamma*s.
#'
#' @return Updated history list with components:
#'   \item{s}{List of step vectors.}
#'   \item{y}{List of gradient differences.}
#'   \item{gamma}{Scaling factor for initial Hessian.}
#'   \item{skipped}{Logical indicating if update was skipped.}
#'
#' @details
#' Unlike L-BFGS, L-SR1 can represent indefinite Hessians and uses a different
#' skip test based on the denominator of the SR1 formula.
#'
#' @keywords internal
update_lsr1 <- function(history, s, y, m = 10L, skip_tol = 1e-8,
                        b_times_s = NULL) {
  # Initialize history if NULL
  if (is.null(history)) {
    history <- list(s = list(), y = list(), gamma = 1.0)
  }

  # Check for zero step vector
  s_norm <- sqrt(sum(s^2))
  if (s_norm < .Machine$double.eps) {
    history$skipped <- TRUE
    return(history)
  }

  # Compute r = y - B*s
  if (is.null(b_times_s)) {
    b_times_s <- history$gamma * s
  }
  r <- y - b_times_s

  # Check for zero residual (B already satisfies secant equation)
  r_norm <- sqrt(sum(r^2))
  if (r_norm < .Machine$double.eps * s_norm) {
    history$skipped <- TRUE
    return(history)
  }

  # SR1 skip test
  denom <- sum(r * s)

  if (abs(denom) < skip_tol * r_norm * s_norm) {
    # Skip this pair
    history$skipped <- TRUE
    return(history)
  }

  # Add new pair
  history$s <- c(history$s, list(s))
  history$y <- c(history$y, list(y))

  # Drop oldest if exceeding memory limit
  k <- length(history$s)
  if (k > m) {
    history$s <- history$s[(k - m + 1):k]
    history$y <- history$y[(k - m + 1):k]
  }

  # Update scaling: gamma = (y'*s) / (s'*s) (Barzilai-Borwein)
  # Only update if positive (required for cubic solver)
  ys <- sum(y * s)
  ss <- sum(s * s)
  if (ss > .Machine$double.eps && ys > .Machine$double.eps) {
    history$gamma <- ys / ss
  }
  # If ys <= 0 (negative curvature), keep previous gamma

  history$skipped <- FALSE
  history
}


#' L-SR1 Hessian-Vector Product
#'
#' Computes the product B*v using the L-SR1 compact representation.
#'
#' @param history L-SR1 history list from `update_lsr1`.
#' @param v Vector to multiply by B.
#'
#' @return The product B*v as a numeric vector.
#'
#' @details
#' The L-SR1 Hessian has the compact form:
#' \deqn{B = \gamma I + \Psi (\Psi^T S)^{-1} \Psi^T}
#' where \eqn{\Psi = Y - \gamma S} and S, Y are matrices of stored vectors.
#'
#' This function computes B*v in O(m^2 + mn) operations.
#'
#' @keywords internal
lsr1_multiply <- function(history, v) {
  k <- length(history$s)

  # Handle empty history - return gamma * v
  if (k == 0) {
    return(history$gamma * v)
  }

  gamma <- history$gamma

  # Compute Psi = Y - gamma*S and Psi^T * v
  psi_v <- numeric(k)
  for (i in 1:k) {
    psi_i <- history$y[[i]] - gamma * history$s[[i]]
    psi_v[i] <- sum(psi_i * v)
  }

  # Build the m x m matrix Psi^T * S
  psi_s <- matrix(0, k, k)
  for (i in 1:k) {
    psi_i <- history$y[[i]] - gamma * history$s[[i]]
    for (j in 1:k) {
      psi_s[i, j] <- sum(psi_i * history$s[[j]])
    }
  }

  # Solve (Psi^T S) * alpha = Psi^T * v
  # Use tryCatch in case matrix is singular
  alpha <- tryCatch(
    solve(psi_s, psi_v),
    error = function(e) rep(0, k)
  )

  # Compute B*v = gamma*v + Psi * alpha
  result <- gamma * v
  for (i in 1:k) {
    psi_i <- history$y[[i]] - gamma * history$s[[i]]
    result <- result + alpha[i] * psi_i
  }

  result
}
