# Quasi-Newton Hessian Update Functions
# ======================================
#
# Implements Algorithm 4a: BFGS, SR1, L-BFGS, and L-SR1 update formulas
# for maintaining Hessian approximations in the QN-ARC optimizer.


#' SR1 (Symmetric Rank-1) Hessian Update
#'
#' Updates the Hessian approximation using the SR1 formula. Unlike BFGS,
#' SR1 can represent indefinite matrices, making it ideal for ARC which
#' naturally handles negative curvature.
#'
#' @param b Current Hessian approximation (n x n symmetric matrix).
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#' @param skip_tol Tolerance for skip test (default: 1e-8). Update is skipped
#'   if |r'*s| < skip_tol * ||r|| * ||s||.
#' @param skip_count Current count of consecutive skipped updates.
#' @param restart_threshold Number of consecutive skips before restart
#'   (default: 5).
#'
#' @return A list with components:
#'   \item{b}{Updated Hessian approximation (n x n matrix).}
#'   \item{skipped}{Logical indicating if update was skipped.}
#'   \item{skip_count}{Updated skip counter (reset to 0 if update applied or
#'     restart triggered).}
#'   \item{restarted}{Logical indicating if b was reset to scaled identity.}
#'
#' @details
#' The SR1 update formula is:
#' \deqn{B_{k+1} = B_k + \frac{r r^T}{r^T s}}
#' where \eqn{r = y - B_k s}.
#'
#' The update is skipped when the denominator is too small relative to the
#' norms of r and s, which prevents numerical instability. After too many
#' consecutive skips, the approximation is reset using Barzilai-Borwein
#' scaling.
#'
#' @references
#' Algorithm 4a in design/pseudocode.qmd
#'
#' Conn, A. R., Gould, N. I., & Toint, P. L. (1991). Convergence of
#' quasi-Newton matrices generated by the symmetric rank one update.
#' Mathematical Programming, 50(1-3), 177-195.
#'
#' @keywords internal
update_sr1 <- function(b, s, y,
                       skip_tol = 1e-8,
                       skip_count = 0L,
                       restart_threshold = 5L) {
  # Compute residual: how far b is from satisfying secant equation
  r <- y - b %*% s
  r <- as.vector(r)

  # Norms for skip test
  r_norm <- sqrt(sum(r^2))
  s_norm <- sqrt(sum(s^2))

  # Skip if s is essentially zero (no step taken)
  if (s_norm < .Machine$double.eps) {
    return(list(b = b, skipped = TRUE, skip_count = skip_count, restarted = FALSE))
  }

  # Skip if r is essentially zero (B already satisfies secant equation)
  if (r_norm < .Machine$double.eps * s_norm) {
    return(list(b = b, skipped = TRUE, skip_count = skip_count, restarted = FALSE))
  }

  # Denominator of SR1 update
  denom <- sum(r * s)

  # Skip test: avoid division by near-zero denominator
  if (abs(denom) >= skip_tol * r_norm * s_norm) {
    # Apply SR1 update: B_{k+1} = B_k + (r r^T) / denom
    b_updated <- b + outer(r, r) / denom

    return(list(
      b = b_updated,
      skipped = FALSE,
      skip_count = 0L,
      restarted = FALSE
    ))
  }

  # Denominator too small - skip update
  skip_count <- skip_count + 1L

  # Check if restart is needed
  if (skip_count > restart_threshold) {
    # Restart with Barzilai-Borwein scaling: gamma = (y'*s) / (s'*s)
    ys <- sum(y * s)
    ss <- sum(s * s)

    if (ss > .Machine$double.eps && abs(ys) > .Machine$double.eps) {
      gamma <- ys / ss
    } else {
      gamma <- 1.0
    }

    # Reset to scaled identity
    n <- length(s)
    b_updated <- gamma * diag(n)

    return(list(
      b = b_updated,
      skipped = TRUE,
      skip_count = 0L,
      restarted = TRUE
    ))
  }

  # Skip without restart
  return(list(
    b = b,
    skipped = TRUE,
    skip_count = skip_count,
    restarted = FALSE
  ))
}


#' BFGS (Broyden-Fletcher-Goldfarb-Shanno) Hessian Update
#'
#' Updates the Hessian approximation using the BFGS formula. BFGS maintains
#' positive definiteness when the curvature condition y'*s > 0 is satisfied.
#'
#' @param b Current Hessian approximation (n x n symmetric positive definite
#'   matrix).
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#'
#' @return A list with components:
#'   \item{b}{Updated Hessian approximation (n x n matrix).}
#'   \item{skipped}{Logical indicating if update was skipped due to curvature
#'     condition violation.}
#'
#' @details
#' The BFGS update formula is:
#' \deqn{B_{k+1} = B_k - \frac{B_k s s^T B_k}{s^T B_k s} + \frac{y y^T}{y^T s}}
#'
#' The update is skipped when the curvature condition \eqn{y^T s > 0} is
#' violated. This can happen on nonconvex problems. When skipped, the previous
#' approximation is retained.
#'
#' Note: BFGS maintains positive definiteness, which wastes ARC's ability to
#' handle indefinite Hessians. Consider using SR1 for nonconvex problems.
#'
#' @references
#' Algorithm 4a in design/pseudocode.qmd
#'
#' Nocedal, J., & Wright, S. J. (2006). Numerical Optimization (2nd ed.).
#' Springer. Section 6.1.
#'
#' @keywords internal
update_bfgs <- function(b, s, y) {
  # Curvature condition: y's > 0 required for positive definiteness
  ys <- sum(y * s)

  if (ys <= .Machine$double.eps) {
    # Curvature condition violated - skip update
    return(list(b = b, skipped = TRUE))
  }

  # Compute B*s for use in update
  bs <- as.vector(b %*% s)
  sbs <- sum(s * bs)

  # BFGS update: B_{k+1} = B_k - (B*s)(B*s)' / (s'*B*s) + y*y' / (y'*s)
  b_updated <- b - outer(bs, bs) / sbs + outer(y, y) / ys

  list(b = b_updated, skipped = FALSE)
}


#' Powell-Damped BFGS Update
#'
#' Applies Powell damping to ensure the curvature condition is satisfied,
#' then performs a BFGS update. This guarantees an update even when the
#' standard curvature condition y's > 0 fails.
#'
#' @param b Current Hessian approximation (n x n symmetric matrix).
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#' @param damping_threshold Threshold for damping (default: 0.2).
#'   Damping applied if y's < damping_threshold * s'Bs.
#'
#' @return A list with components:
#'   \item{b}{Updated Hessian approximation (n x n matrix).}
#'   \item{theta}{Damping parameter used (1.0 = no damping).}
#'   \item{y_damped}{The damped y vector used in update.}
#'   \item{skipped}{Logical indicating if update was skipped (only if s'Bs
#'     is too small to apply damping).}
#'
#' @details
#' Powell damping modifies y to y_damped = theta*y + (1-theta)*Bs such that
#' s'*y_damped >= damping_threshold * s'*Bs, ensuring positive curvature.
#'
#' The formula for theta when y's < damping_threshold * s'Bs is:
#' theta = (1 - damping_threshold) * s'Bs / (s'Bs - y's)
#'
#' This ensures s'*y_damped = damping_threshold * s'Bs exactly.
#'
#' @references
#' Powell, M. J. D. (1978). A fast algorithm for nonlinearly constrained
#' optimization calculations. Numerical Analysis, 144-157.
#'
#' Algorithm 4a-hybrid in design/pseudocode.qmd
#'
#' @keywords internal
update_bfgs_powell <- function(b, s, y, damping_threshold = 0.2) {
  # Compute B*s and curvature terms

  bs <- as.vector(b %*% s)
  sbs <- sum(s * bs)
  ys <- sum(y * s)

  # Guard: if s'Bs is too small, we can't apply damping safely

  if (sbs <= .Machine$double.eps) {
    return(list(b = b, theta = NA_real_, y_damped = y, skipped = TRUE))
  }

  # Determine if damping is needed
  if (ys >= damping_threshold * sbs) {
    # No damping needed - use standard BFGS
    theta <- 1.0
    y_damped <- y
  } else {
    # Apply Powell damping
    # theta chosen so s'*y_damped = damping_threshold * s'Bs
    theta <- (1 - damping_threshold) * sbs / (sbs - ys)
    y_damped <- theta * y + (1 - theta) * bs
  }

  # Apply BFGS with (possibly damped) y
  ys_damped <- sum(y_damped * s)
  b_updated <- b - outer(bs, bs) / sbs + outer(y_damped, y_damped) / ys_damped

  list(b = b_updated, theta = theta, y_damped = y_damped, skipped = FALSE)
}


#' Hybrid BFGS/SR1 Update with Automatic Routing
#'
#' Attempts BFGS first, falls back to SR1, then to Powell-damped BFGS.
#' Provides robust quasi-Newton updates for both convex and nonconvex regions.
#'
#' @param b Current Hessian approximation (n x n symmetric matrix).
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#' @param bfgs_tol Tolerance for BFGS curvature condition (default: 1e-10).
#' @param sr1_skip_tol Tolerance for SR1 skip test (default: 1e-8).
#' @param skip_count Current count of consecutive skipped updates.
#' @param restart_threshold Number of consecutive skips before restart
#'   (default: 5).
#'
#' @return A list with components:
#'   \item{b}{Updated Hessian approximation (n x n matrix).}
#'   \item{update_type}{Character: "bfgs", "sr1", "powell", or "skipped".}
#'   \item{skipped}{Logical indicating if no update was applied.}
#'   \item{skip_count}{Updated skip counter (reset on successful update).}
#'   \item{restarted}{Logical indicating if b was reset to scaled identity.}
#'   \item{theta}{Powell damping parameter (only if update_type = "powell").}
#'
#' @details
#' Routing priority:
#' 1. BFGS if y's > bfgs_tol (stable, positive definite)
#' 2. SR1 if |r's| >= sr1_skip_tol * ||r|| * ||s|| (allows indefiniteness)
#' 3. Powell-damped BFGS otherwise (guaranteed update)
#'
#' The hybrid approach is ideal for problems that transition between
#' convex and nonconvex regions.
#'
#' @references
#' Algorithm 4a-hybrid in design/pseudocode.qmd
#'
#' @keywords internal
update_hybrid <- function(b, s, y,
                          bfgs_tol = 1e-10,
                          sr1_skip_tol = 1e-8,
                          skip_count = 0L,
                          restart_threshold = 5L) {
  # Early exit for zero step
  s_norm <- sqrt(sum(s^2))
  if (s_norm < .Machine$double.eps) {
    return(list(
      b = b,
      update_type = "skipped",
      skipped = TRUE,
      skip_count = skip_count,
      restarted = FALSE,
      theta = NA_real_
    ))
  }

  # Curvature for BFGS check

  ys <- sum(y * s)

  # 1. TRY BFGS (stable, maintains positive definiteness)
  if (ys > bfgs_tol) {
    bs <- as.vector(b %*% s)
    sbs <- sum(s * bs)

    if (sbs > .Machine$double.eps) {
      b_updated <- b - outer(bs, bs) / sbs + outer(y, y) / ys
      return(list(
        b = b_updated,
        update_type = "bfgs",
        skipped = FALSE,
        skip_count = 0L,
        restarted = FALSE,
        theta = NA_real_
      ))
    }
  }

  # 2. FALL BACK TO SR1 (allows indefiniteness)
  r <- y - as.vector(b %*% s)
  r_norm <- sqrt(sum(r^2))
  denom <- sum(r * s)

  # Skip SR1 if r is essentially zero (B already satisfies secant equation)
  # or if denominator condition is met
  if (r_norm >= .Machine$double.eps * s_norm &&
      abs(denom) >= sr1_skip_tol * r_norm * s_norm) {
    b_updated <- b + outer(r, r) / denom
    return(list(
      b = b_updated,
      update_type = "sr1",
      skipped = FALSE,
      skip_count = 0L,
      restarted = FALSE,
      theta = NA_real_
    ))
  }

  # 3. FALL BACK TO POWELL-DAMPED BFGS (guaranteed update)
  powell_result <- update_bfgs_powell(b, s, y)

  if (!powell_result$skipped) {
    return(list(
      b = powell_result$b,
      update_type = "powell",
      skipped = FALSE,
      skip_count = 0L,
      restarted = FALSE,
      theta = powell_result$theta
    ))
  }

  # All methods failed - skip update (very rare edge case)
  skip_count <- skip_count + 1L

  # Check if restart is needed
  if (skip_count > restart_threshold) {
    # Restart with Barzilai-Borwein scaling
    ss <- sum(s * s)
    if (ss > .Machine$double.eps && abs(ys) > .Machine$double.eps) {
      gamma <- ys / ss
    } else {
      gamma <- 1.0
    }
    n <- length(s)
    b_updated <- abs(gamma) * diag(n)  # Use abs to ensure positive scaling

    return(list(
      b = b_updated,
      update_type = "skipped",
      skipped = TRUE,
      skip_count = 0L,
      restarted = TRUE,
      theta = NA_real_
    ))
  }

  # Skip without restart
  list(
    b = b,
    update_type = "skipped",
    skipped = TRUE,
    skip_count = skip_count,
    restarted = FALSE,
    theta = NA_real_
  )
}


# =============================================================================
# Limited-Memory Variants
# =============================================================================
# These functions work with history lists instead of explicit matrices.
# The Hessian is represented implicitly via two-loop recursion.


#' L-BFGS History Update
#'
#' Updates the L-BFGS history by adding a new (s, y) pair and dropping the
#' oldest if the memory limit is exceeded.
#'
#' @param history List with components `s` (list of step vectors) and `y`
#'   (list of gradient differences). Can be NULL for first iteration.
#' @param s New step vector: s = x_new - x_old.
#' @param y New gradient difference: y = g_new - g_old.
#' @param m Maximum number of pairs to store (default: 10).
#'
#' @return Updated history list with components:
#'   \item{s}{List of step vectors (most recent last).}
#'   \item{y}{List of gradient differences.}
#'   \item{rho}{Vector of 1/(y'*s) values for each pair.}
#'   \item{gamma}{Scaling factor for initial Hessian: (y'*s)/(y'*y).}
#'
#' @details
#' L-BFGS stores the m most recent (s, y) pairs and represents the Hessian
#' implicitly. The scaling gamma is the Barzilai-Borwein estimate from the
#' most recent pair.
#'
#' @keywords internal
update_lbfgs <- function(history, s, y, m = 10L) {
  # Curvature condition check
  ys <- sum(y * s)

  if (ys <= .Machine$double.eps) {
    # Skip this pair - curvature condition violated
    if (is.null(history)) {
      return(list(s = list(), y = list(), rho = numeric(0), gamma = 1.0))
    }
    return(history)
  }

  # Initialize history if NULL
  if (is.null(history)) {
    history <- list(s = list(), y = list(), rho = numeric(0), gamma = 1.0)
  }

  # Add new pair
  history$s <- c(history$s, list(s))
  history$y <- c(history$y, list(y))
  history$rho <- c(history$rho, 1.0 / ys)

  # Drop oldest if exceeding memory limit
  k <- length(history$s)
  if (k > m) {
    history$s <- history$s[(k - m + 1):k]
    history$y <- history$y[(k - m + 1):k]
    history$rho <- history$rho[(k - m + 1):k]
  }

  # Update scaling: gamma = (y'*s) / (y'*y) from most recent pair
  yy <- sum(y * y)
  if (yy > .Machine$double.eps) {
    history$gamma <- ys / yy
  }

  history
}


#' L-BFGS Two-Loop Recursion
#'
#' Computes the product B*g using the two-loop recursion algorithm, where B
#' is the L-BFGS approximation represented by the history.
#'
#' @param history L-BFGS history list from `update_lbfgs`.
#' @param g Vector to multiply by B (typically the gradient).
#'
#' @return The product B*g as a numeric vector.
#'
#' @details
#' The two-loop recursion computes B*g in O(mn) operations where m is the
#' history length and n is the dimension, avoiding explicit formation of the
#' n x n matrix B.
#'
#' The algorithm:
#' 1. Backward loop: compute alpha_i and update q
#' 2. Initial scaling: r = gamma * q
#' 3. Forward loop: update r using beta_i
#'
#' @references
#' Nocedal, J., & Wright, S. J. (2006). Numerical Optimization (2nd ed.).
#' Springer. Algorithm 7.4.
#'
#' @keywords internal
lbfgs_multiply <- function(history, g) {
  k <- length(history$s)

  # Handle empty history - return gamma * g
  if (k == 0) {
    return(history$gamma * g)
  }

  # Allocate storage for alpha values
  alpha <- numeric(k)

  # First loop: go backwards through history
  q <- g
  for (i in k:1) {
    alpha[i] <- history$rho[i] * sum(history$s[[i]] * q)
    q <- q - alpha[i] * history$y[[i]]
  }

  # Initial Hessian: H_0 = gamma * I
  r <- history$gamma * q

  # Second loop: go forwards through history
  for (i in 1:k) {
    beta <- history$rho[i] * sum(history$y[[i]] * r)
    r <- r + (alpha[i] - beta) * history$s[[i]]
  }

  r
}


#' L-BFGS Hessian-Vector Product (B*v)
#'
#' Computes B*v (Hessian approximation times vector) from L-BFGS history.
#' Note: This is different from \code{\link{lbfgs_multiply}} which computes
#' H*v (inverse Hessian times vector).
#'
#' @param history L-BFGS history list with components `s`, `y`, `rho`, `gamma`.
#'   Can be NULL (returns gamma*v or just v if gamma not available).
#' @param v Vector to multiply (length n).
#' @param gamma Initial scaling. If NULL, uses history$gamma or 1.0.
#'
#' @return B*v where B is the L-BFGS Hessian approximation.
#'
#' @details
#' Uses compact form representation: B = gamma*I + Psi * inv(M) * Psi'
#' where Psi = Y - gamma*S and M = Psi' * S.
#'
#' This is needed for Powell damping in L-Hybrid, which requires s^T B s.
#'
#' @keywords internal
lbfgs_multiply_b <- function(history, v, gamma = NULL) {
  # Determine gamma
  if (is.null(gamma)) {
    gamma <- if (!is.null(history) && !is.null(history$gamma)) {
      history$gamma
    } else {
      1.0
    }
  }

  # Handle NULL or empty history - B = gamma*I
  if (is.null(history) || length(history$s) == 0) {
    return(gamma * v)
  }

  k <- length(history$s)
  n <- length(v)

  # Build S and Y matrices (n x k)
  s_mat <- do.call(cbind, history$s)
  y_mat <- do.call(cbind, history$y)

  # Psi = Y - gamma * S (n x k)
  psi <- y_mat - gamma * s_mat

  # M = Psi^T * S (k x k) - this is lower triangular for BFGS
  m_mat <- t(psi) %*% s_mat

  # Compute Psi^T * v (k x 1)
  psi_v <- as.vector(t(psi) %*% v)

  # Solve M * alpha = Psi^T * v for alpha
  alpha <- tryCatch(
    solve(m_mat, psi_v),
    error = function(e) {
      # If M is singular, fall back to pseudoinverse
      svd_result <- svd(m_mat)
      tol <- .Machine$double.eps * max(dim(m_mat)) * max(svd_result$d)
      d_inv <- ifelse(svd_result$d > tol, 1 / svd_result$d, 0)
      as.vector(svd_result$v %*% (d_inv * (t(svd_result$u) %*% psi_v)))
    }
  )

  # B*v = gamma*v + Psi * alpha
  gamma * v + as.vector(psi %*% alpha)
}


#' Limited-Memory Hybrid BFGS/SR1 Update
#'
#' Limited-memory version of \code{\link{update_hybrid}}. Routes between L-BFGS,
#' L-SR1, and Powell-damped L-BFGS based on curvature conditions.
#'
#' @param history L-Hybrid history list with s, y, gamma. Can be NULL.
#' @param s Step vector: s = x_new - x_old.
#' @param y Gradient difference: y = g_new - g_old.
#' @param m Maximum number of pairs to store (default: 10).
#' @param bfgs_tol BFGS curvature tolerance (default: 1e-10).
#' @param sr1_skip_tol SR1 skip threshold (default: 1e-8).
#' @param damping_threshold Powell damping threshold (default: 0.2).
#'
#' @return A list with components:
#'   \item{history}{Updated history structure with s, y, gamma.}
#'   \item{update_type}{"lbfgs", "lsr1", or "powell".}
#'   \item{theta}{Damping parameter (1.0 if no damping applied).}
#'
#' @details
#' Routing priority:
#' 1. L-BFGS if y'*s > bfgs_tol (stable, positive definite)
#' 2. L-SR1 if SR1 denominator OK (allows indefiniteness)
#' 3. Powell-damped L-BFGS (guaranteed update)
#'
#' Uses a unified history format (s, y, gamma) compatible with both
#' lbfgs_compact_form and lbfgs_multiply_b. Does not use rho since we
#' don't need the two-loop recursion (lbfgs_multiply).
#'
#' This is Algorithm 4a-lhybrid from design/pseudocode.qmd.
#'
#' @keywords internal
update_lhybrid <- function(history, s, y, m = 10L,
                           bfgs_tol = 1e-10,
                           sr1_skip_tol = 1e-8,
                           damping_threshold = 0.2) {
  # Compute curvature
  ys <- sum(y * s)

  # Initialize history if NULL
  if (is.null(history)) {
    history <- list(s = list(), y = list(), gamma = 1.0)
  }

  gamma <- history$gamma

  # Compute B*s (needed for SR1 check and Powell damping if BFGS fails)
  b_s <- lbfgs_multiply_b(history, s, gamma)

  # Determine which y to store and update type
  y_to_store <- y
  update_type <- "lbfgs"
  theta <- 1.0

  # 1. TRY L-BFGS (stable, positive definite)
  if (ys > bfgs_tol) {
    # L-BFGS path: store original y
    y_to_store <- y
    update_type <- "lbfgs"
    theta <- 1.0
  } else {
    # 2. FALL BACK TO L-SR1 (allows indefiniteness)
    r <- y - b_s
    r_norm <- sqrt(sum(r * r))
    s_norm <- sqrt(sum(s * s))
    denom <- sum(r * s)

    # SR1 skip test (need r_norm > 0 to be meaningful)
    if (r_norm >= .Machine$double.eps * s_norm &&
        abs(denom) >= sr1_skip_tol * r_norm * s_norm) {
      # L-SR1 path: store original y (allows negative curvature)
      y_to_store <- y
      update_type <- "lsr1"
      theta <- 1.0
    } else {
      # 3. FALL BACK TO POWELL-DAMPED L-BFGS (guaranteed update)
      sbs <- sum(s * b_s)

      # Guard against non-positive s'Bs
      if (sbs <= .Machine$double.eps) {
        # Cannot apply Powell damping safely, store original y
        y_to_store <- y
        update_type <- "lbfgs"
        theta <- NA_real_
      } else {
        # Apply Powell damping
        if (ys < damping_threshold * sbs) {
          theta <- (1 - damping_threshold) * sbs / (sbs - ys)
          y_to_store <- theta * y + (1 - theta) * b_s
        } else {
          theta <- 1.0
          y_to_store <- y
        }
        update_type <- "powell"
      }
    }
  }

  # Add pair to history
  history$s <- c(history$s, list(s))
  history$y <- c(history$y, list(y_to_store))

  # Trim to m pairs if exceeding memory limit
  k <- length(history$s)
  if (k > m) {
    history$s <- history$s[(k - m + 1):k]
    history$y <- history$y[(k - m + 1):k]
  }

  # Update gamma (Barzilai-Borwein scaling from stored y)
  ys_stored <- sum(y_to_store * s)
  yy_stored <- sum(y_to_store * y_to_store)
  if (yy_stored > .Machine$double.eps) {
    history$gamma <- ys_stored / yy_stored
  }

  list(
    history = history,
    update_type = update_type,
    theta = theta
  )
}


#' L-SR1 History Update
#'
#' Updates the L-SR1 history by adding a new (s, y) pair if it passes the
#' skip test.
#'
#' @param history List with components `s`, `y`, and `gamma`. Can be NULL.
#' @param s New step vector: s = x_new - x_old.
#' @param y New gradient difference: y = g_new - g_old.
#' @param m Maximum number of pairs to store (default: 10).
#' @param skip_tol Tolerance for skip test (default: 1e-8).
#' @param b_times_s Product B*s where B is current approximation. If NULL,
#'   uses gamma*s.
#'
#' @return Updated history list with components:
#'   \item{s}{List of step vectors.}
#'   \item{y}{List of gradient differences.}
#'   \item{gamma}{Scaling factor for initial Hessian.}
#'   \item{skipped}{Logical indicating if update was skipped.}
#'
#' @details
#' Unlike L-BFGS, L-SR1 can represent indefinite Hessians and uses a different
#' skip test based on the denominator of the SR1 formula.
#'
#' @keywords internal
update_lsr1 <- function(history, s, y, m = 10L, skip_tol = 1e-8,
                        b_times_s = NULL) {
  # Initialize history if NULL
  if (is.null(history)) {
    history <- list(s = list(), y = list(), gamma = 1.0)
  }

  # Check for zero step vector
  s_norm <- sqrt(sum(s^2))
  if (s_norm < .Machine$double.eps) {
    history$skipped <- TRUE
    return(history)
  }

  # Compute r = y - B*s
  if (is.null(b_times_s)) {
    b_times_s <- history$gamma * s
  }
  r <- y - b_times_s

  # Check for zero residual (B already satisfies secant equation)
  r_norm <- sqrt(sum(r^2))
  if (r_norm < .Machine$double.eps * s_norm) {
    history$skipped <- TRUE
    return(history)
  }

  # SR1 skip test
  denom <- sum(r * s)

  if (abs(denom) < skip_tol * r_norm * s_norm) {
    # Skip this pair
    history$skipped <- TRUE
    return(history)
  }

  # Add new pair
  history$s <- c(history$s, list(s))
  history$y <- c(history$y, list(y))

  # Drop oldest if exceeding memory limit
  k <- length(history$s)
  if (k > m) {
    history$s <- history$s[(k - m + 1):k]
    history$y <- history$y[(k - m + 1):k]
  }

  # Update scaling: gamma = (y'*s) / (s'*s) (Barzilai-Borwein)
  # Only update if positive (required for cubic solver)
  ys <- sum(y * s)
  ss <- sum(s * s)
  if (ss > .Machine$double.eps && ys > .Machine$double.eps) {
    history$gamma <- ys / ss
  }
  # If ys <= 0 (negative curvature), keep previous gamma

  history$skipped <- FALSE
  history
}


#' L-SR1 Hessian-Vector Product
#'
#' Computes the product B*v using the L-SR1 compact representation.
#'
#' @param history L-SR1 history list from `update_lsr1`.
#' @param v Vector to multiply by B.
#'
#' @return The product B*v as a numeric vector.
#'
#' @details
#' The L-SR1 Hessian has the compact form:
#' \deqn{B = \gamma I + \Psi (\Psi^T S)^{-1} \Psi^T}
#' where \eqn{\Psi = Y - \gamma S} and S, Y are matrices of stored vectors.
#'
#' This function computes B*v in O(m^2 + mn) operations.
#'
#' @keywords internal
lsr1_multiply <- function(history, v) {
  k <- length(history$s)

  # Handle empty history - return gamma * v
  if (k == 0) {
    return(history$gamma * v)
  }

  gamma <- history$gamma

  # Compute Psi = Y - gamma*S and Psi^T * v
  psi_v <- numeric(k)
  for (i in 1:k) {
    psi_i <- history$y[[i]] - gamma * history$s[[i]]
    psi_v[i] <- sum(psi_i * v)
  }

  # Build the m x m matrix Psi^T * S
  psi_s <- matrix(0, k, k)
  for (i in 1:k) {
    psi_i <- history$y[[i]] - gamma * history$s[[i]]
    for (j in 1:k) {
      psi_s[i, j] <- sum(psi_i * history$s[[j]])
    }
  }

  # Solve (Psi^T S) * alpha = Psi^T * v
  # Use tryCatch in case matrix is singular
  alpha <- tryCatch(
    solve(psi_s, psi_v),
    error = function(e) rep(0, k)
  )

  # Compute B*v = gamma*v + Psi * alpha
  result <- gamma * v
  for (i in 1:k) {
    psi_i <- history$y[[i]] - gamma * history$s[[i]]
    result <- result + alpha[i] * psi_i
  }

  result
}
